const SETLOGINSTATUS = 'SETLOGINSTATUS'
const SETINFO = 'SETINFO'
const SETHEADERTEXT = 'SETHEADERTEXT'
const SETHEADERRIGHTTEXT = 'SETHEADERRIGHTTEXT'
export { SETLOGINSTATUS, SETINFO, SETHEADERTEXT, SETHEADERRIGHTTEXT }
